version: '3.7'
services:
  mariadb1:
    container_name: mariadb-master
    image: mariadb
    ports:
      - "13306:3306"
    command: --lower_case_table_names=1    
    environment:
      MYSQL_ROOT_PASSWORD: root1234!@
      TZ: Asia/Seoul

  mariadb2:
    container_name: mariadb-slave
    image: mariadb
    ports:
      - "13307:3306"
    command: --lower_case_table_names=1    
    environment:
      MYSQL_ROOT_PASSWORD: root1234!@
      TZ: Asia/Seoul